### ISSUE TITLE
Circumvent using (pseudo) async call

### ISSUE THREAD

**Issue by LittleFinix** [Fordi/BlockEvil#2]
The detection can be circumvented by using `setTimeout`, as the actual call-site won't show up in the stack trace:
```javascript
function queryAsync(q, cb)
{
  setTimeout(() => {
    let el = document.querySelector(q);
    cb(el);
  }, 0);
}

eval("queryAsync('#test', el => el.innerHTML = 'It Works!')");
```
jsFiddle: https://jsfiddle.net/Littlefinix/0fymc9vs/37/

I'm not sure how this can be prevented... we'll probably need to replace `setTimeout` in the userscript and use its original call-site when detecting calls to any of the 'bad' functions. Something like this:
```javascript
const originalSetTimeout = setTimeout;
setTimeout = function() {
  const stack = getStackTrace(); // get stack trace from somewhere
  const fn = arguments[0]; // first argument should be the callback
  const safeFn = function() {
    setContext(stack); // <-- tell noEval to check this stack trace as well
    return fn.apply(this, arguments);
  };
  return originalSetTimeout.apply(this, [ safeFn ].concat(arguments.slice(1)));
};
```
Although, I haven't tested this.

It would need to be done for `setInterval` as well, of course.

Some good news is it requires at least a bit of effort to replace all the calls to `querySelector`, etc. with async ones. However, this could be made relatively easy with `Promise`s and `async`/`await`, and possibly a precompiler like Babel or TypeScript.

**Comment by Fordi** [comment]
Solved it by making setInterval / setTimeout / requestAnimationFrame wrap the passed function in a function named `eval` if an eval stack is detected at the time the async'r is called.
